spring:
  application:
    name: app-powerbi
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    ec.fin.powerbi: DEBUG
    org.springframework.security: INFO
    org.springframework.ldap: DEBUG
    javax.naming: WARN
    com.sun.jndi: WARN


