spring:
  application:
    name: app-powerbi
# CONFIGURACION DEL AD - PROTON


# POWER BI
# PROTON

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:coopsanjose_fin_ec2025.pfx
    key-store-password: '**Ecuador.2025!!'
    key-store-type: PKCS12

logging:
  level:
    ec.fin.powerbi: DEBUG
    org.springframework.security: INFO
    org.springframework.ldap: DEBUG
    javax.naming: WARN
    com.sun.jndi: WARN


